### PR TITLE
feature: use tox for testing

### PR DESCRIPTION
**Pull request by psafont**
Move test automization to test from travis, this allows to easily test outside of travis

### CODE REVIEW

**Comment by psafont** [comment]
For some reason in Travis there are way more tests passing than in my local machine :smile:

**Comment by adamstruck** [comment]
For those failing 7 tests I wonder if they are the same ones that were marked as unsupported features in the last successful build (https://travis-ci.org/common-workflow-language/cwl-tes/jobs/327356336)...

**Comment by adamstruck** [comment]
Otherwise this looks like a nice improvement! I have never tried using tox before.

**Comment by psafont** [comment]
I've seen that the package published lacks the readme, so I took he liberty to add it, this is how it looks like (on the test pypi): https://test.pypi.org/project/cwl-tes-random/

I could also add git-tag-based package version instead of parsing `__init__.py` with regex.


Is there any way to add the 7 failing tests to unsupported if they are ideed the failing ones?

**Comment by adamstruck** [comment]
Thanks for updating the README as well. 

As far as versioning goes, I prefer to use semantic versioning. 

I suspect the reason they are failing rather than being marked as unsupported may have something to do with your updating the `cwltest` version

**Comment by psafont** [comment]
The git-tag-based system is only to avoid repetition, set the (semantic) version as a tag and the package version comes for free.
The only change it would produce is that untagged commits would compile to a package version with the closest tagin the predecessors with the commit's hash appended. e.g. `2.0.0-65b8c0f`.

As for the tests, before this PR the cwltest version was not upper-bound in requirements.txt. I'll check if fixing a particular version solves the issue.

**Comment by psafont** [comment]
Huh, it's failing when building the package on python 3.4, it works fine on my machine :/

**Comment by psafont** [comment]
Alternatively I can conly allow 2.7, 3.5 and 3.6, as it is on master. I've tried to debug the build on travis, but couldn't find why

**Pull request merged**
