### PR TITLE
[WIP] freshen cwltool, cwltest versions

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by adamstruck** [comment]
I'd prefer to get #16 than just bump the versions.

**Comment by mr-c** [comment]
Ah, I have more commits coming here. I don't know anything about funnel, but I do know cwltool (and the big breaking changes we made) so maybe we could start with the cwltool side first?

**Comment by adamstruck** [comment]
Sorry, the other PR's name is misleading.  The main purpose of it was to substantially simplify the `cwl-tes` code base to rely more heavily on `cwltool`.

**Comment by adamstruck** [comment]
I bumped the version as you did in the other PR, but now realize that cwltool made substantial changes (i.e. no more kwargs being pass around). 

Either work from this PR or take over / fork my previous one. Whatever is easiest for you.

**Comment by mr-c** [comment]
@adamstruck This PR doesn't make use of the new parallel runner yet, so lets start with it and then continue with #16 once https://github.com/common-workflow-language/cwltool/pull/800 is done

**Pull request merged**
