### PR TITLE
updates to use new cwltool code and bump funnel version for testing

### PR DESCRIPTION
**Pull request by adamstruck**
Since cwltool added the parallel mode (https://github.com/common-workflow-language/cwltool/pull/566) I found I could simply the cwl-tes codebase substantially. 

~However, due to some issues in cwltool many of the conformance tests are now failing due to https://github.com/common-workflow-language/cwltool/issues/689~

~- [ ] bypass the `cwltool` resource accounting~

### CODE REVIEW

**Comment by psafont** [comment]
May be worth putting the funnel version as a variable into the travis script and define the URL based on it ;)

**Comment by mr-c** [comment]
@adamstruck I've had some progress here. Maybe you could take a look?

**Comment by adamstruck** [comment]
I'd test against funnel version 0.8.0 - it shouldn't require any code changes. That should help clean up the travis logs.  Looks like with the latest cwltool version there is only 1 test that is failing.  I'll try and take a look later today.

**Comment by adamstruck** [comment]
The final test that is failing is: `[122] Test InitialWorkDirRequirement with a nested directory structure from another step`

This is due to how Funnel handles output directories that are empty. The first step of the workflow in this test creates an empty directory.  Funnel doesn't do anything since the directory is empty. We chose this behavior for consistency with object stores since they don't have the concept of a directory. 

My thought is to modify the conformance test so the nested directory from the first step isn't empty.  @mr-c what do you think?

**Comment by mr-c** [comment]
Thank you @adamstruck 

We can have an additional CWL conformance test with non-empty directories, but there is no reason to change a conformance test that is spec-valid and working on other CWL engines just because it doesn't currently work on **this** engine 🙂

While Funnel may choose to not store empty directories, it can at least report them as they are easy to represent in CWL even without a `location`

Looks like the TES spec doesn't forbid either empty input or empty output directories. 

For output directories Funnel could just create the empty directory locally and return a file:/// URI

**Comment by adamstruck** [comment]
Since you can't represent an empty directory in an object store, we chose to have Funnel ignore empty output directories in the local file storage plugin to make it consistent with our object store storage plugins. 

Funnel could do what you mention above and then make object stores behave similarly by adding some hidden empty file. 

Maybe its fine to just have cwl-tes fail this one conformance test and get this merged in anyways.

**Comment by mr-c** [comment]
As long as that hidden empty file is removed on staging then that works for me.

👍 To merging (preferably with the rest of the tests still being required)

**Pull request merged**
