### PR TITLE
WIP: initial support for ftp locations

### PR DESCRIPTION
**Pull request by mr-c**
Current status: 121 tests passed, 4 failures, 8 unsupported features

- [x] separate storage of inputs, intermediate products, and final outputs
- [x] test for correct handling of file naming conflicts
- [ ] general cleanup

### CODE REVIEW

**Comment by fgypas** [comment]
Will this solve the issue #26 ? Can you add an ftp example?

**Comment by mr-c** [comment]
@fgypas That's the goal, but I'm having issues testing

**Comment by mr-c** [comment]
```
[job bwa-mem-tool.cwl] Removing temporary directory /tmp/tmp0gyepo6l
Removing intermediate output directory /tmp/tmpyc7cwp6s
{
    "args": [
        "bwa",
        "mem",
        "-t",
        "2",
        "-I",
        "1,2,3,4",
        "-m",
        "3",
        "chr20.fa",
        "example_human_Illumina.pe_1.fastq",
        "example_human_Illumina.pe_2.fastq"
    ]
}
Final process status is success
```

**Comment by fgypas** [comment]
Hi. I would like to ask what is the status of this pull request. We would really need to have this working at the end of the month. Please let me know if there is anything I could do to help.

**Comment by aniewielska** [comment]
Hi. I second the request by @fgypas. What is the status of remote storage support? How to run it? Could you provide an example with FTP? I tried hashsplitter, passing --remote-storage-url, but without success.

**Comment by mr-c** [comment]
Hello @fgypas and @aniewielska 
Here are the latest results with the conformance tests being run against the EBI TASK endpoint:

> 32 tests passed, 87 failures, 13 unsupported features

The complete log

To run the CWL conformance tests, check out the CWL specification https://github.com/common-workflow-language/common-workflow-language/

[log-20180825.txt](https://github.com/common-workflow-language/cwl-tes/files/2353600/log-20180825.txt)

```
pip install cwltest html5lib
./run_test.sh RUNNER=cwl-tes EXTRA="--remote-storage-url ftp://ftp-private.ebi.ac.uk/upload/cwl_conf002 --tes https://tes-dev.tsi.ebi.ac.uk/"
```
You'll need the username and password set in `${HOME}/.netrc` see https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html
Mine looks like
```
machine ftp-private.ebi.ac.uk
login redacted_username
password redacted_password
```

**Comment by aniewielska** [comment]
Thanks. I figured out .netrc part. Should Hashsplitter work, though, with remote FTP storage? If not, is there any other simple at least 2-step workflow (that will use intermediate remote storage, if configured, or local otherwise), that I can use to check, that I am using CWL-TES correctly?

**Comment by mr-c** [comment]
@aniewielska Hashsplitter and friends should work, but it doesn't due to a limitation in `cwltool` in how file sizes are calculated; which I'm working on now.

Here's how to run it
```
cwl-tes --remote-storage-url ftp://ftp-private.ebi.ac.uk/upload/some_unique_name --tes https://tes-dev.tsi.ebi.ac.uk/ tests/hashsplitter-md5.cwl.yml --input tests/resources/test.txt 
```

**Comment by mr-c** [comment]
@aniewielska The hashsplitter tools and workflows work for me now:

```
cwl-tes  --remote-storage-url ftp://ftp-private.ebi.ac.uk/upload/unique_directory_002 \
    --tes https://tes-dev.tsi.ebi.ac.uk/ tests/hashsplitter-workflow.cwl.yml \
    --input tests/resources/test.txt 
```

**Comment by mr-c** [comment]
At least 31 more conformance tests are now passing; thank you @aniewielska

**Comment by aniewielska** [comment]
Hi. That is great! I managed to run HashSplitter and some conformance tests from the suite on Python3.5, but have issues with Python2.7 -> I am getting:

`cwltool-1.0.20180906112546-py2.7.egg/cwltool/command_line_tool.py", line 691, in collect_output
tests/hashsplitter-md5.cwl.yml:25:5:     with fs_access.open(rfile["location"], "rb") as f:
tests/hashsplitter-md5.cwl.yml:25:5:
tests/hashsplitter-md5.cwl.yml:25:5: AttributeError: addinfourl instance has no attribute '__exit__'`

The same thing is happening, by running full suite. 
For Python3.5 it is running fine, though the final output in a local file system is missing (should it get downloaded from FTP?) and logs are informing that it was produced.

When running the full suite on python 3.5,  I am running into issues with parsing json (the JSON object must be str, not 'bytes').

**Comment by mr-c** [comment]
@aniewielska Thanks!

I think I have fixed the `addinfourl` error. Can you provide more information on the other error?

**Comment by mr-c** [comment]
Summary of current errors:
12 Tests related to scattering: 
(no execution failures, but wrong results)
- Test single step workflow with Scatter step
- Test single step workflow with Scatter step and two data links connected to same input, default merge behavior
- Test single step workflow with Scatter step and two data links connected to same input, nested merge behavior
- Test workflow scatter with single scatter parameter
- Test workflow scatter with two scatter parameters and nested_crossproduct join method
- Test workflow scatter with two scatter parameters and flat_crossproduct join method
- Test workflow scatter with two scatter parameters and dotproduct join method
- Test workflow scatter with single scatter parameter and two valueFrom on step input (first and current el)
- Test workflow scatter with two scatter parameters and nested_crossproduct join method and valueFrom on step input
- Test workflow scatter with two scatter parameters and flat_crossproduct join method and valueFrom on step input
- Test workflow scatter with two scatter parameters and dotproduct join method and valueFrom on step input
- Test workflow scatter with single scatter parameter and two valueFrom on step input (current el twice)

Default inputs with local `file:///` locations need to be uploaded and rewritten
- Test default value on step input parameter
- Test use default value on step input parameter with empty source
- Test use default value on step input parameter with null source

Reading `cwl.output.json` from the remote URL
- Test support for reading cwl.output.json when running in a Docker container and just 'path' is provided.
- Test support for reading cwl.output.json when running in a Docker container and just 'location' is provided.

A possible file naming bug? (API endpoint timed out)
- Test workflow two input files with same name

A cluster of failed tests involving directories:
- Test directory input with parameter reference
- Test directory input in Docker
- Test directory output
- Test directories in secondaryFiles
- Test directory input with inputBinding
- Test InitialWorkDirRequirement with a nested directory structure from another step

InitialWorkDirRequirement issues:
- Test dynamic initial work dir
- Test expression in InitialWorkDir listing
- Test output of InitialWorkDir

Misc:
- Test $HOME and $TMPDIR are set correctly in Docker
- Test secondaryFiles on array of files.
- Test that nameroot and nameext are generated from basename at execution time by the runner
- Test that OutputBinding.glob is sorted as specified by POSIX
- Test successCodes

Known unsupported feature that could be supported:
- Test dynamic resource reqs referencing inputs

**Comment by aniewielska** [comment]
1) Context manager change helped for Python 2.7, but I think I still get errors for a couple more tests, than only those mentioned above (will check it again and come back). Those mentioned above also fail.
2) In case of Hashsplitter (again) - I cannot see the final output file in my local filesystem (although, logs inform, that it has bean indeed produced). Is downloading the final output from FTP supported?
3) AFAIK scatter/gathers run 2 tasks in parallel with the same output file path on remote FTP. So the result is random (one task overwrites results of the second one).

**Comment by mr-c** [comment]
@aniewielska Good catch about the output directories; that was already on my list but is now the obvious next task.

**Comment by mr-c** [comment]
@aniewielska Copying back from the remote location isn't part of my contract with EMBL-EBI, sorry.

**Comment by fgypas** [comment]
Hi @aniewielska 

Can I have access to this ftp server (ftp://ftp-private.ebi.ac.uk)? 
Who should I contact to create me an account?

Thank you in advance
Foivos

**Comment by fgypas** [comment]
Update: I just tried with a user that does not contain the **@** character, but I still get the same error.

**Comment by mr-c** [comment]
Hello @fgypas 
`ftplib.error_perm: 550 Can't check for file existence` implies that your FTP server doesn't support the SIZE command. If you know of another way to check to file existance that works with your server I would gladly accept a patch

**Comment by mr-c** [comment]
@adamstruck The remaining errors are related to TES's poor support for empty directories. Shall I merge as in?

**Comment by aniewielska** [comment]
I ran the test suite yesterday (without the most recent commits) and I got: 

``110 tests passed, 11 failures, 12 unsupported features 
1 tool tests failed ``

From the TESK perspective there were 7 tasks failing on inputs. In 5 cases TES received inputs with URLs referencing local file system. In 2 cases passed URL was malformed (file/ftp mix):

``{"url": "file://ftp%3A//ftp-private.ebi.ac.uk/upload/anie/test-1/7f123688-c414-4a46-b9ea-087570c60112/ref.fasta",
            "path": "/SesUIM/ref.fasta", "type": "FILE", "name": "ref.fasta", "description":
            "InitialWorkDirRequirement:cwl_input:ref.fasta"}``

**Comment by adamstruck** [comment]
@mr-c prior to merging this I think it would be good to update the Travis build so that it runs the conformance suite against local files and FTP. 

We have some test code in Funnel (https://github.com/ohsu-comp-bio/funnel/tree/master/tests/ftp-test-server) for starting up a FTP server for testing that could be reused.

**Comment by geoffjentry** [comment]
What we were told when working on CWL in GCP (and thus object storage) was to add a dotfile to the directory so that it shows up in object storage as a "directory".

IMO that's a terrible hack and frankly a bug in CWL (and soon to be replicated in WDL as well) that it doesn't neatly handle the impedance mismatch between POSIX & object storage, but it's not like I have any better idea on how to solve it so c'est la vie. Dotfiles it is :)

With my GA4GH hat on I personally would oppose things which are not object storage friendly (it **is** the **Cloud** Workstream after all).

**Comment by mr-c** [comment]
For my reference, the failing test numbers are: 
- 55
- 60
- 77
- 84
- 85 
- 87
- 88
- 91
- 93 
- 101
- 121
- 122

**Pull request merged**
